# Generated by Django 2.1.4 on 2019-01-18 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_typetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallets.Category')),
                ('type_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.TypeTransaction')),
            ],
        ),
    ]
